### ISSUE TITLE
Dedicated sections for libwpe and WPEBackend-fdo?

### ISSUE THREAD

**Issue by philn** [Igalia/wpewebkit.org#1]
I think these 2 components should appear more prominently on the website. The first is a direct dependency of WPE and the second is an important optional dependency :)

**Comment by philn** [comment]
For now I had to dig in the "release announcements" section, which doesn't feel very intuitive.

**Comment by aperezdc** [comment]
Somewhat related: PR #6 makes the downloads for these components more visible in the main page, which I think is a step in the right direction :smiley:

**Comment by bkardell** [comment]
These would definitely, I think be in the architecture section, right? That has a button right in the 'hero' place which is currently hidden because we havent' written it, but I don't think you could get more prominent than that -- wdyt @philn ?  With @aperezdc's change and that - will this probably fulfill this enhancement if we get there?

**Comment by philn** [comment]
Maybe :)
I was just looking the new website again now and got scared for a bit, couldn't find download links. Then I found the "Code" section and my heart beat improved.

**Comment by philn** [comment]
Let's close this since iiuc libwpe and WPEBackend-fdo are doomed.
