### ISSUE TITLE
FAQ brainstorming

### ISSUE THREAD

**Issue by philn** [Igalia/wpewebkit.org#26]
- Is Wayland required to run WPE?
- What is this wayland-protocols build dependency about in Cog?
- Are open dialogs/popups menus supported?
- What's up with EME? How can I support this feature in my WPE-based product?
- What's the status regarding WebRTC? Why is libwebrtc disabled?
- What is the difference between WebPlatformForEmbedded's WPE and WPEWebKit?

**Comment by bkardell** [comment]
* What is (and isn't) cog? 
* Something isn't working for me... help? (flatpak, rpi, etc?)
* What Web features does WPE support?

**Comment by calvaris** [comment]
**What's up with EME? How can I support this feature in my WPE-based product?**

There is code in WebKit to support EME but in any case you will need a license to access it since this part is not open source. There are three ways you can get this working:

A. Getting a license and use the Thunder OCDM plugin.
B. Write a Thunder compatible API complement that will glue with your DRM system.
C. Write a new CDM backend for WebKit using your DRM system.

**Comment by aperezdc** [comment]
Maybe this is not exactly FAQ material, but we often get people stuck with some gotchas while trying to get WPE to work. Maybe they can be formatted as questions and answers somehow. For example:

Q: Why does the browser/launcher (e.g. Cog) crash at startup?
A: If you are building an embedded system image yourself, make sure there is at least one font installed that can be used as fallback and that Fontconfig knows about it.
