### ISSUE TITLE
Improving /about/supported-hardware.md

### ISSUE THREAD

**Issue by meyerweb** [Igalia/wpewebkit.org#71]
The current layout of https://wpewebkit.org/about/supported-hardware.html is a little jumbled, so I propose to clarify it a bit.

**Comment by meyerweb** [comment]
@aperezdc, a question about this page—specifically, the table headings.  They seem inconsistent in the first column: three are “Device”, two “SoC”, and one “Series”, with another just skipping straight to “GPU”.  Is there any way to make them consistent?  Should they be consistent?

Also, with some of the tables, there are “n/a” cells and blank cells.  Is there a meaningful distinction between the two states, or can any empty cell be filled with an “n/a”?  Similarly, can missing cells (some rows are too short) be restored with an “n/a”?

**Comment by aperezdc** [comment]
I think we can unify “Device”, “SoC“, and “Series” and use the “Device” heading in all cases (a SoC is a devices after all, for example).

The table that does not have a “Device” column is because on PCs it would always have the value “Any”: for those what matters is the actual GPU model, and the rest does not really matter to be able to say whether WPE will run there or not. I suppose we could add the missing column in that table, slap “Any” as device there, and call it a day :thinking:

**Comment by aperezdc** [comment]
Regarding the white cells vs. “n/a”:

- The “n/a“ means “not applicable” and is only on the “Cog Shells” column. The value means that WPE is known to run on the device, but the known and tested configuration used some other browser/launcher that is not Cog.
- The empty cells are plainly missing, because when the page was first written I tried to ask people around what they were using, but I did not always get answers. So for example I know someone that had at some point WPE running on a RK3399 based device with the Panfrost driver, and while I suspect that was with the “fdo” backend, we do not have a confirmation.
